CREATE VIEW VACCOUNTBALANCE AS
(
SELECT
    SUM( MOVEMENTS.MOVEMENT ) AS BALANCE, ACCOUNTS.ENTITYID + ' ' + ACCOUNTS.OFFICEID + ' ' + ACCOUNTS.CDID + ' ' + ACCOUNTS.ANID AS ACCOUNTNUMBER,
    ACCOUNTS.ACCOUNTID, ACCOUNTS.ENTITYID, ACCOUNTS.OFFICEID, ACCOUNTS.CDID, ACCOUNTS.ANID, ACCOUNTS.STARTDATE, ACCOUNTS.ENDDATE,
    ACCOUNTS.INTERESRATE, ACCOUNTS.ACCOUNTTYP
FROM
    PUBLIC.ACCOUNTS
        LEFT JOIN PUBLIC.MOVEMENTS ON
            ACCOUNTS.ACCOUNTID = MOVEMENTS.ACCOUNTID
GROUP BY
    ACCOUNTS.ACCOUNTID
    );

select * from VACCOUNTBALANCE;